name: Rebase
on:
  push:
    branches:
      - nixos-unstable-bootspec-patched
  workflow_dispatch: # run manually
  schedule:
  - cron: "0 23 * * *" # run once a day

jobs:
  sync_latest_nixos-unstable_from_upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Rebase nixos-unstable-bootspec-patched against nixos-unstable
      id: sync_nixos
      shell: bash
      run: |
        set +x
        git config --global user.email "action@github.com"
        git config --global user.name "GH Action - Upstream Sync"
        git checkout nixos-unstable-bootspec-patched
        git remote add upstream https://github.com/NixOS/nixpkgs.git || true
        git fetch upstream nixos-unstable
        git rebase upstream/nixos-unstable
        git push --force-with-lease
  sync_latest_nixpkgs-unstable_from_upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Rebase nixpkgs-unstable-bootspec-patched against nixpkgs-unstable
      id: sync_nixpkgs
      shell: bash
      run: |
        set +x
        git config --global user.email "action@github.com"
        git config --global user.name "GH Action - Upstream Sync"
        git checkout nixpkgs-unstable-bootspec-patched
        git remote add upstream https://github.com/NixOS/nixpkgs.git || true
        git fetch upstream nixpkgs-unstable
        git rebase upstream/nixpkgs-unstable
        git push --force-with-lease
